language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - rustup component add clippy
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy -- -D warnings
matrix:
  allow_failures:
    - rust: nightly
